### ISSUE TITLE
How to clamp mss to pmtu on tailscale interface?

### ISSUE THREAD

**Issue by fghorow** [jack-broadway/vyos-module-tailscale#12]
I'm attempting to configure [site-to-site](https://tailscale.com/kb/1214/site-to-site) routing on a `tailscale0` interface created by this infrastructure.

I'm using a sagitta VyOS 1.4.0-rc3 core .iso and your module to build my install `.iso`. (Works very well, BTW. Thank you!!!)

One of the things in the tailscale instructions for site-to-site is to configure `clamp mss to pmtu` on that interface.

Because when I try to execute `set interface tailscale ...`  and tailscale is not recognized in that config mode, I can't figure out how to set that clamp-mss-to-pmtu configuration. Is this something that needs to be patched (somewhere?) in this codebase? If so, where? (I can take a crack at it, but I'm lost in the vyos codebase, not to mention your additions.)

Any help would be greatly appreciated!

**Comment by jack-broadway** [comment]
Hi @fghorow  after having a quick look through the vyos docs this is implemented for other interface types so it should be more than possible to implement for the tailscale interface. I'll have a look over the coming weekend

**Comment by jack-broadway** [comment]
@fghorow Try with the following config when building and let me know if it solves you're issue. I can see the rule get create in nftables.

This does require version 2.2.0 of `vyos-modular` so please update first

```yml
name: tailscale-1.4.0-rc3
vyos_target:
  # This is used to target an appropriate vyos-core version when using modules
  # that patch the core
  branch: 1.4.0-rc3
  release: sagitta
  # This is the name of an iso found under resources/isos
  iso: vyos-1.4.0-rc3-amd64.iso
modules:
  - type: git
    url: https://github.com/jack-broadway/vyos-module-tailscale.git
    version: issue-12
```
